import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/layout/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-auto p-5 h-[100vh]`}>
        
        <main className='max-w-screen-lg mx-auto px-4 py-3 bg-slate-100/70 rounded-lg h-[100%]'>
          <Header/>
          {children}
        </main>
      </body>
    </html>
  )
}

